# Generated by Django 5.0.4 on 2024-04-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availableQty',
            new_name='available_qty',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prize',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='qtySold',
            new_name='qty_sold',
        ),
    ]
