# Generated by Django 5.0.4 on 2024-04-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_rename_availableqty_product_available_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='orders',
        ),
    ]
